<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Authors>Grant Colley</Authors>
	<Copyright>Copyright © 2026, Grant Colley. All rights reserved</Copyright>	  
    <AssemblyName>DevelopmentInProgress.TradeServer.StrategyExecution.WebHost</AssemblyName>
    <RootNamespace>DevelopmentInProgress.TradeServer.StrategyExecution.WebHost</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="System.Reactive" Version="6.1.0" />
    <PackageReference Include="System.Reactive.Linq" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\tradeview\src\DevelopmentInProgress.Socket\DevelopmentInProgress.Socket.csproj" />
    <ProjectReference Include="..\..\..\tradeview\src\DevelopmentInProgress.TradeView.Core\DevelopmentInProgress.TradeView.Core.csproj" />
    <ProjectReference Include="..\..\..\tradeview\src\DevelopmentInProgress.TradeView.Service\DevelopmentInProgress.TradeView.Service.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.Socket.Extensions\DevelopmentInProgress.Socket.Extensions.csproj" />
  </ItemGroup>

</Project>
