<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Authors>Grant Colley</Authors>
	<Copyright>Copyright © 2026, Grant Colley. All rights reserved</Copyright>
    <StartupObject></StartupObject>
    <AssemblyName>DevelopmentInProgress.TradeServer.Console</AssemblyName>
    <RootNamespace>DevelopmentInProgress.TradeServer.Console</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\tradeview\src\DevelopmentInProgress.TradeView.Core\DevelopmentInProgress.TradeView.Core.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeServer.StrategyExecution.WebHost\DevelopmentInProgress.TradeServer.StrategyExecution.WebHost.csproj" />
  </ItemGroup>

</Project>
