<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
	<Authors>Grant Colley</Authors>
	<Copyright>Copyright © 2020, Grant Colley. All rights reserved</Copyright>
	<UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\output\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\accounts.png" />
    <None Remove="Images\Server.png" />
    <None Remove="Images\ServerMonitor.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.2" />
    <PackageReference Include="Prism.Core" Version="9.0.537" />
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
	<PackageReference Include="System.Reactive" Version="6.1.0" />
	<PackageReference Include="System.Reactive.Core" Version="6.1.0" />
	<PackageReference Include="System.Reactive.Linq" Version="6.1.0" />
	<PackageReference Include="System.Reactive.PlatformServices" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Wpf.Common\DevelopmentInProgress.TradeView.Wpf.Common.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Wpf.Controls\DevelopmentInProgress.TradeView.Wpf.Controls.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Wpf.Host.Controller\DevelopmentInProgress.TradeView.Wpf.Host.Controller.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Accounts.png" />
    <Resource Include="Images\Connection.png" />
    <Resource Include="Images\Dashboard.png" />
    <Resource Include="Images\NotRunning.png" />
    <Resource Include="Images\Running.png" />
    <Resource Include="Images\Server.png" />
    <Resource Include="Images\ServerMonitor.png" />
    <Resource Include="Images\Strategy.png" />
  </ItemGroup>

</Project>
