<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
	<Authors>Grant Colley</Authors>
	<Copyright>Copyright © 2020, Grant Colley. All rights reserved</Copyright>
    <UseWPF>true</UseWPF>
    <NeutralLanguage>en-GB</NeutralLanguage>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\output\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.2" />	  
    <PackageReference Include="Prism.Core" Version="9.0.537" />
	<PackageReference Include="Prism.Unity" Version="9.0.537" />
	<PackageReference Include="Prism.Wpf" Version="9.0.537" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
	<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="TradeView.ThirdParty.Docking" Version="1.0.0" />
    <PackageReference Include="TradeView.ThirdParty.Docking.Themes.Aero" Version="1.0.0" />
    <PackageReference Include="TradeView.ThirdParty.Docking.Themes.VS2013.NETCore" Version="1.0.0" />
	<PackageReference Include="Unity.Abstractions" Version="5.11.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevelopmentInProgress.Strategy.MovingAverage.Wpf\DevelopmentInProgress.Strategy.MovingAverage.Wpf.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Core\DevelopmentInProgress.TradeView.Core.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Data.File\DevelopmentInProgress.TradeView.Data.File.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Data\DevelopmentInProgress.TradeView.Data.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Wpf.Common\DevelopmentInProgress.TradeView.Wpf.Common.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Wpf.Configuration\DevelopmentInProgress.TradeView.Wpf.Configuration.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Wpf.Controls\DevelopmentInProgress.TradeView.Wpf.Controls.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Wpf.Dashboard\DevelopmentInProgress.TradeView.Wpf.Dashboard.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Wpf.Host.Controller\DevelopmentInProgress.TradeView.Wpf.Host.Controller.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Wpf.Strategies\DevelopmentInProgress.TradeView.Wpf.Strategies.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Wpf.Trading\DevelopmentInProgress.TradeView.Wpf.Trading.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\close.png" />
    <Resource Include="Images\GroupListItem.png" />
    <Resource Include="Images\Log.png" />
    <Resource Include="Images\Origin.png" />
    <Resource Include="Images\Refresh.png" />
    <Resource Include="Images\Save.png" />
    <Resource Include="Images\SaveAll.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>