<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	<Authors>Grant Colley</Authors>
	<Copyright>Copyright © 2026, Grant Colley. All rights reserved</Copyright>
	<IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
	<PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
	<PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
	<PackageReference Include="coverlet.collector" Version="6.0.4">
	 <PrivateAssets>all</PrivateAssets>
	 <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
    <PackageReference Include="Prism.Core" Version="9.0.537" />
	<PackageReference Include="System.Reactive" Version="6.1.0" />
	<PackageReference Include="System.Reactive.Linq" Version="6.1.0" />	  
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DevelopmentInProgress.TradeView.Core\DevelopmentInProgress.TradeView.Core.csproj" />
    <ProjectReference Include="..\..\src\DevelopmentInProgress.TradeView.Wpf.Common\DevelopmentInProgress.TradeView.Wpf.Common.csproj" />
    <ProjectReference Include="..\..\src\DevelopmentInProgress.TradeView.Wpf.Trading\DevelopmentInProgress.TradeView.Wpf.Trading.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="UserAccounts.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
