<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
	<Authors>Grant Colley</Authors>
	<Copyright>Copyright © 2020, Grant Colley. All rights reserved</Copyright>
	<UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\output\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.2" />
	<PackageReference Include="Prism.Core" Version="9.0.537" />
	<PackageReference Include="Prism.Wpf" Version="9.0.537" />
	<PackageReference Include="System.Reactive" Version="6.1.0" />
	<PackageReference Include="System.Reactive.Core" Version="6.1.0" />
	<PackageReference Include="System.Reactive.Interfaces" Version="6.1.0" />	  
	<PackageReference Include="System.Reactive.Linq" Version="6.1.0" />
	<PackageReference Include="System.Reactive.PlatformServices" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Core\DevelopmentInProgress.TradeView.Core.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Service\DevelopmentInProgress.TradeView.Service.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Wpf.Common\DevelopmentInProgress.TradeView.Wpf.Common.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Wpf.Controls\DevelopmentInProgress.TradeView.Wpf.Controls.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Wpf.Host.Controller\DevelopmentInProgress.TradeView.Wpf.Host.Controller.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Wpf.Strategies\DevelopmentInProgress.TradeView.Wpf.Strategies.csproj" />
    <ProjectReference Include="..\DevelopmentInProgress.TradeView.Wpf.Trading\DevelopmentInProgress.TradeView.Wpf.Trading.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\accounts.png" />
    <Resource Include="Images\configuration.png" />
    <Resource Include="Images\manageServers.png" />
    <Resource Include="Images\manageStrategies.png" />
  </ItemGroup>

</Project>
